Fix IcarusWorker.notify_canceled() TypeError.
Commit 96e8970 added a "graceful" argument to the workers'
notify_canceled() methods.  This didn't get added to IcarusWorker,
which results in a period exception in the logs:

 Exception while canceling job: Traceback (most recent call last):
   File "/usr/local/lib/mpbm/core/job.py", line 144, in cancel
     try: self.worker.notify_canceled(self, graceful)
 TypeError: notify_canceled() takes exactly 2 arguments (3 given)

The exception seems harmless, but the fix is trivial.